from assistant.fields.field import Field
from assistant.fields.address import Address
from assistant.fields.date import Date
from assistant.fields.email_address import EmailAddress
from assistant.fields.name import Name
from assistant.fields.phone import Phone
from assistant.fields.tag import Tag
from assistant.fields.text import Text
from assistant.fields.title import Title
