from assistant.fields.field import *
from assistant.fields.address import *
from assistant.fields.date import *
from assistant.fields.email_address import *
from assistant.fields.name import *
from assistant.fields.phone import *
from assistant.fields.tag import *
from assistant.fields.text import *
from assistant.fields.title import *